apiVersion: v1
kind: Service
metadata:
  name: udacitycapstone
spec:
  type: LoadBalancer
  selector:
    app: udacitycapstone
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitycapstone-deploy
spec:
  selector:
    matchLabels:
      app: udacitycapstone
  replicas: 5
  template:
    metadata:
      labels:
        app: udacitycapstone
    spec:
      containers:
      - name: udacitycapstone-pod
        image: ankit0910/finalcapstone:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10